# Site settings
title:        Taylor Edwards
description:  >
              Taylor Edwards is a UX/UI designer in Seattle.l
baseurl:      /
url:          "http://www.tayloredwards.net"

github:       "https://github.com/Rumudiez/"
twitter:      "https://twitter.com/Rumudiez/"

# Build settings
markdown: kramdown